<?php include '../components/header.php';?>            
<?php include '../components/navigation.php';?>            
<?php include '../components/sidemenu.php';?> 

<div class="container"><section class="py-5"><h1 class="font-weight-bolder text-center text-capitalize text-dark font-family-san-serif font-size-3pt5rem px-3">complaints</h1></section><section class="py-3 case-study-left-padding pull-left"><div class="col-12 col-sm-12 col-md-12 col-lg-12 col-xl-12 pull-left" style="float: inherit;"><p>Symbio Energy has always provided our customers with our best services. We are committed to supplying the UK with the Lowest Prices for Electricity and deliver an excellent customer service experience that is clear and concise.</p><p>&nbsp;</p><p></p><p>Should there be an instance that you have a complaint or issue with our services, we shall quickly manage to resolve your queries.</p><p></p><p>Our Customer Service Agents are trained to deal with complaints professionally and reliably. Our agents will do everything possible to provide with a solution to your queries and complaints promptly.</p><p>We shall explain the resolution process and walk you through the steps the same. Regular contact will be maintained until your query has been resolved.</p><p><br><strong>STEP 1: Contact Customer Services</strong></p><p>If you have a query about your electricity, feel free to contact our dedicated customer service agents for a resolution.</p><p>We aim to provide you with a solution within five working days and be rest assured that we will only close your complaint once you are pleased with the outcome.</p><p>In case of complex issues, it can take up to 28 working days to resolve and keep you updated on the progress.</p><p><br>
When contacting us with your complaint, please state your customer reference number (if applicable) and let us know the nature of your complaint regarding our service, products, or failures of standards in marketing and sales.</p><p>Our response will include an apology, an explanation and remediation along with any financial compensation wherever applicable.</p><p><br>
If you have any queries, please do not hesitate to contact us. Please email us at customerservices@symbioenergy.co.uk or call us on 0333 050 9372, we are available from Monday to Friday between 09:00 am to 06:00 pm.</p><p>&nbsp;</p><p><strong>STEP 2: Internal Review by Quality Assurance Team</strong></p><p>If you don't feel your complaint has been resolved after the first step, get in touch with our Quality Assurance Team. We will conduct a full review and will take the necessary action to make things right. A dedicated agent will be assigned to you to resolve your issues and aim to resolve the same within ten working days.</p><p><br>
Please email us at customerservices@symbioenergy.co.uk or call us on 0333 050 9372, we are available from Monday to Friday between 09:00 am to 06:00 pm.</p><p><br>
Alternatively, you can write to the Quality Assurance Team at SYMBIO ENERGY 103 MANSION HOUSE, BUILDING RESEARCH ESTABLISHMENT, BUCKNALLS LANE, WATFORD, UNITED KINGDOM, WD25 9XX.</p><p>We will aim to reach a mutual agreement, and we achieve this in most cases. If we cannot reach an agreement, we will write to you explaining the position and providing our final offer.</p><p><br><strong>STEP 3: External Review - Ombudsman Services (Energy)</strong></p><p>We will do our best to resolve your complaint and ensure that you are happy with the outcome which happens in most cases. However, there may be cases where we cannot agree and reach a resolution.</p><p>In such cases, we will send you a final resolution letter known as a 'Deadlock Letter'. If it has been eight weeks or more since you have first complained, you have a statutory right to contact the Ombudsman Services for a free and independent review of your concerns.</p><p><br>
Contact Details:</p><p>Ombudsman Services: Energy contact details</p><p>Telephone: 0330 440 1624 (Mon-Fri, 9am – 5pm)</p><p>Website:&nbsp;<a data-auth="NotApplicable" href="https://www.ombudsman-services.org/" rel="noreferrer noopener" tabindex="-1" target="_blank" title="https://www.ombudsman-services.org/">www.ombudsman-services.org/energy</a></p><p>Address: Ombudsman Services: Energy, PO Box 966, Warrington, WA4 9DF</p><p>&nbsp;</p><p><br><strong>Independent Advice: Citizen Advice Consumer Helpline</strong></p><p>The Citizen Advice Consumer Helpline is an official source for free and independent energy advice. The customer can consult them at any stage during the complaint process. They can help you 'Know your Rights' as an Energy Consumer, find a better deal, find out how to make a complaint, get advice about the quality of your electricity supply, or ask for help if you are struggling to pay your bills.</p><p><br>
To 'know your rights' contact the Citizens Advice Consumer Helpline:</p><p>Telephone number:</p><p>Consumer Service – 0808 223 1133</p><p>Consumer Service Speaking Welsh – 0808 223 1144</p><p>(lines open Monday to Friday 9.00 am to 5.00 pm)</p><p><br>
Website address:&nbsp;<a data-auth="NotApplicable" href="https://www.citizensadvice.org.uk/energy/" rel="noreferrer noopener" tabindex="-1" target="_blank" title="https://www.citizensadvice.org.uk/energy/">www.citizensadvice.org.uk/energy</a></p><p>Address: Citizens Advice consumer service, Second Floor, Fairfax House, Merrion Street, Leeds LS2 8JU</p><p>Email queries:&nbsp;<a data-auth="NotApplicable" href="https://ssl.datamotion.com/form.aspx?co=3438&amp;frm=post&amp;to=flarepost.fromforms" rel="noreferrer noopener" tabindex="-1" target="_blank" title="https://ssl.datamotion.com/form.aspx?co=3438&amp;frm=post&amp;to=flarepost.fromforms">Citizens Advice online form</a></p></div></section></div>

<?php include '../components/footer.php';?>